### ISSUE TITLE
Describe various aspects of what ropensci reviews

### ISSUE THREAD

**Issue by karthik** [karthik/cise#12]
> Maybe for each section here, describe briefly what they actually mean? People not familiar with software might not know, for example, what documentation actually is. Would help this paper appeal to a wider audience.

I'm not sure what to do here. This is the special issue of computing in science and technology on open source software. I can see how terms like CI might be hard for a lay reader to grasp but documentation?

**Comment by maelle** [comment]
I'm puzzled too. But it's easy enough to put "elements such as software manuals" since there are other elements that we want to ignore in their review 😀

**Comment by karthik** [comment]
I suppose this could be covered by #14 if we add a little box describing what "documentation" is.
