### ISSUE TITLE
Clarify terms

### ISSUE THREAD

**Issue by karthik** [karthik/cise#14]
>  Page 6, lines 46-49, I have pretty much no idea what any of these things are. I think given that you are trying to make the case that software sustainability, and its advantages, are useful for the wider research community, being careful to explain any specialist terms like this is important for accessibility.

Our reviewer who doesn't write software is asking about documentation, continuous integration, testing etc. I suppose we could have a definitions box in the paper.

**Comment by karthik** [comment]
Actually I have no idea what page 6, line 46-49 is in the original google doc https://docs.google.com/document/d/1MLJrWZmvdgbfuaco_TyB-xBBQU9TQQyrEtJyDpF_LXY/edit#

**Comment by maelle** [comment]
Yes to the definition box, and we could add a sentence about how we try to make such things accessible to newbies by our guidelines including (links) well beginner-friendly resources, and support.

**Comment by karthik** [comment]
Even a paper about documentation doesn’t' actually define documentation.  ¯\_(ツ)_/¯
https://arxiv.org/pdf/1805.12398.pdf

![image](https://user-images.githubusercontent.com/138494/46683725-894e0400-cc0e-11e8-9584-2b804dfab829.png)


I'm at a loss for what to include in this list of terms besides continuous integration (if we skip documentation)

**Comment by karthik** [comment]
I clarified CI inline like so:

> lack of continuous integration (services that allow for the software to be tested any time a change is made to the code) for testing
