### ISSUE TITLE
Sidebar discussion

### ISSUE THREAD

**Issue by karthik** [karthik/cise#16]
> Is it not a bit weird again that we are still submitting software to the same incentive systems that are based around journal systems? Does the increasing importance of software trigger the need for a greater diversification of research evaluation processes, rather than just a narrow focus on citations? For example, the research community digests and re-uses software much more differently than it does for research papers, and this means that we need to look at different ways of providing credit for these things (see here for some discussion on this matter: https://academic.oup.com/femsle/advance-article/doi/10.1093/femsle/fny204/5078345).

>  For example, we don’t want to just provide incentives for engagement, but for high quality engagements, which is possible through software-based process which are more collaborative, and a sort of ‘reviewing the reviewers’ system. So it might be possible to do things like create virtual rewards such as points, badges, or abilities that capture the altruistic nature of software development and couple it to the development of researcher profiles. Having incentives based on social processes rather than journal brands seems like a nice future to me.

**Comment by maelle** [comment]
mmmh anyway IMO rOpenSci already does both by having a list of reviewers in the onboarding repo + dev_guide, encouraging thanking reviewers, inviting reviewers&authors to a Slack, etc.

**Comment by karthik** [comment]
I added this to one of the bullet points that talks about benefits of ropensci peer review

> rOpenSci additionally recognizes all reviewers in the developer guide book and also en-courages software authors to acknowledge reviewers in the software metadata.

**Comment by maelle** [comment]
Nice. Are blog post links ok? Noam wrote a good one about the rev role

**Comment by karthik** [comment]
Yeah. A bunch of the posts are already cited at the end of the paper.
