### ISSUE TITLE
What is unsustainable?

### ISSUE THREAD

**Issue by karthik** [karthik/cise#2]
> It might help readers here to clarify explicitly what you mean by ‘unsustainable’.

**Comment by maelle** [comment]
"in particular, with undocumented manual steps depending on the expertise of temporary staff, and on untracked software dependencies"?

**Comment by karthik** [comment]
"undocumented manual steps" seems confusing to me. What do you mean by that? I could write a R package that is extremely well documented but have a bus factor of 1 and abandon the project at some point because I don't have funding to work on it. 

Similar with untracked dependencies, I'm not sure what you mean.  To install, every R/Python package needs to list dependencies. A software could be unsustainable because I never updated it after it stopped being compatible with a dependency and no one else was able to fix it. 

Does that make sense?

I took a stab at keeping it more general without using unsustainable:

Old:


> Despite its importance, much of academic software is developed in a highly unsustainable manner and contributes to a variety of problems that afflict modern science

New

> Despite its importance, a large proportion of academic software is developed in an ad hoc manner with little regard for the high standards characteristic of other research activities. As a result, the research software ecosystem is fragile and the source of numerous problems that afflict modern computational science.

thoughts?

**Comment by maelle** [comment]
sounds good, if you have space you could add examples of fragility (like the bus factor you mention)

**Comment by karthik** [comment]
Updated text.
