### ISSUE TITLE
Precise link between unsustainable software → reproducible research

### ISSUE THREAD

**Issue by karthik** [karthik/cise#3]
> Can you make it clearer what the precise link between unsustainable software and the reproducibility crises is?

**Comment by maelle** [comment]
I think that #2 will help

**Comment by karthik** [comment]
I think this is an important critique. I'm not sure where to add this link explicitly. Here is a stab at the end of the first paragraph of the introduction. Please suggest improvements (this is a draft)

> When research software is inaccessible, lacks adequate usage instructions, is difficult to install, lacks adequate tests, or is poorly maintained, it can impede efforts to reproduce results generated using such tools.

**Comment by maelle** [comment]
It looks fine but I'd like to see "broken" in it somewhere.

> When research software is inaccessible, lacks adequate usage instructions, is difficult to install, lacks adequate tests, or is poorly maintained, it can impede efforts to reproduce results generated using such tools or even prevent them completely by unexpectedly breaking.

🤔

**Comment by karthik** [comment]
Good point. I tired to work it in there but failed.

**Comment by karthik** [comment]
I put in in the text but the sentence does not read well and needs to be reworked.
