### ISSUE TITLE
Author bios

### ISSUE THREAD

**Issue by karthik** [karthik/cise#4]
For the CISE article, I will need a short bio from each of you. Can you please post to this thread and I will add it to the doc? 🙏 

- [x] Scott 
- [x] Carl 
- [ ] Stefanie 
- [ ] Noam
- [x] Maëlle

**Comment by maelle** [comment]
Maëlle Salmon is a volunteer editor, and a part-time software engineer at rOpenSci. Contact her via https://masalmon.eu/

**Comment by cboettig** [comment]
> Carl Boettiger is an assistant professor in the department of Environmental Science, Policy, and Management at UC Berkeley and a member of the rOpenSci leadership team.  Contact him at cboettig@berkeley.edu.

**Comment by sckott** [comment]
> Scott Chamberlain is a co-founder of and software developer with rOpenSci. Contact him at scott@ropensci.org

**Comment by karthik** [comment]
Added tentative bios for Noam and Stefanie

**Comment by stefaniebutland** [comment]
updated mine in doc you shared
