### ISSUE TITLE
Mention the reviewers work

### ISSUE THREAD

**Issue by karthik** [karthik/cise#7]
> Page 2, Line 44: I think these are just collectively known as ‘The Carpentries’ now? Also, the Open Science MOOC (which I run) is working on training students/researchers more on these things too (see eg here), which might be worth mentioning. I’m obviously biased..

🙄 Can we punt on this and say we don't know enough about this training or its impact to say anything for this paper? There is plenty published about the carpentries and the impact of their work over several years. Thoughts?

**Comment by maelle** [comment]
😩 Yes I'd say that in such a short publication we prefer focusing on a single example that is published.

**Comment by karthik** [comment]
> The reviewer is correct in that the umbrella organization is known as The Carpentries. However the workshops are still distinctly offered as software and data carpentry and our focus is on those efforts. While we appreciate additional suggestions for training programs to mention, the two distinct types of courses we mention (university and non-university) serve to make the point.
