### ISSUE TITLE
Clarify "us"

### ISSUE THREAD

**Issue by karthik** [karthik/cise#8]
> Page 2, Line 54: Who is ‘us’?

**Comment by karthik** [comment]
Replaced 

>  a subset of us 

with

> a subset of the authors

**Comment by maelle** [comment]
You could even put your initials after that.

**Comment by karthik** [comment]
Several of us have considered these issues so it doesn't make sense to add my initials after.

**Comment by maelle** [comment]
I mean the initials of the subset of authors who did that, but that's not compulsory.

**Comment by karthik** [comment]
ok, will see what others think. This comment feels silly to me. Given we have listed authors at the top of the paper, us means the authors.
